import type { AlbumData } from "../../engine/album";

export const ALBUM: AlbumData = {
  meta: {
    id: "beni-buyuten-sarkilar-vol-1",
    artist: "Hayko Cepkin",
    album: "Beni Büyüten Şarkılar Vol.1",
    year: "2015",
    cover: "covers/beni-buyuten-sarkilar-vol1.jpg",
    accent: "#ff8a4c",
    accentInk: "#1a0703",
    displayFont: "'Sedgwick Ave Display', cursive",
    font3d: "sedgwick-400",
    description:
      "Kapaktaki gibi bir anne karnının içindesin. Hayko'yu büyüten dokuz şarkı, zarın içinde süzülen anı kabarcıklarında saklı. Her şarkı bir ay; sen dinledikçe bebek büyüyor.",
    mechanic: {
      name: "Dokuz Ay",
      text: "Süzülen anı kabarcıklarına yaklaş ve E ile patlat; içinden çıkan plağı gramofona tak. Şarkı çalarken solundaki zara dışarıdaki dünyanın gölgeleri düşer ve hikâye sözlerle birlikte perde perde ilerler; gölgelere bakıp E ile anıya dokun, bebek tekmeler. Şarkıların belli anlarında zarın içinde hatıra eşyaları belirir. Her şarkı bir ay: bebek büyür, kalp hızlanır. Dokuzuncu şarkı bittiğinde doğum anı gelir.",
    },
    controls: [
      { keys: "W A S D", label: "Yürü" },
      { keys: "Fare", label: "Bak" },
      { keys: "Shift", label: "Koş" },
      { keys: "Boşluk", label: "Zıpla" },
      { keys: "E", label: "Kabarcığı patlat · plağı tak · anıya dokun" },
      { keys: "Q", label: "Elindekini bırak" },
      { keys: "R", label: "Çal / durdur" },
      { keys: "G", label: "Gramofonu kucağına al / yere koy" },
      { keys: "V", label: "Şarkının klibini izle / serbest dolaş" },
      { keys: "K", label: "Klibi kapat / aç (müzik sürer)" },
      { keys: "T", label: "Bakış açısı: birinci / üçüncü kişi" },
      { keys: "ESC", label: "Menü ve ayarlar" },
    ],
    credits: [
      "Hayko Cepkin — Beni Büyüten Şarkılar Vol.1 · 29 Aralık 2015 · DMC",
      "Hayko Cepkin'i büyüten şarkıların yeniden yorumları",
      "Şarkılar resmi YouTube kaynaklarından çalınır.",
    ],
  },
  tracks: [
    { id: "ben-insan-degil-miyim", order: 1, title: "Ben İnsan Değil Miyim", videoId: "pEpP_Oo5LSs", mood: "Sıcak bir lamba, eski bir kaset: insan olmanın ilk sesi.", credit: "Söz: Sait Ergenç · Müzik: Muhammed Abdülvahab" },
    { id: "aldirma-gonul", order: 2, title: "Aldırma Gönül", videoId: "GC7wzPXAiUM", mood: "Duvarın ardında deniz; gönül parmaklıklara aldırmıyor.", credit: "Şiir: Sabahattin Ali · Beste: Kerem Güney" },
    { id: "o-cesme", order: 3, title: "O Çeşme", videoId: "QndaKMq8EJE", mood: "Bir çeşmenin başında bekleyen eski bir hatıra.", credit: "Söz-Müzik: Mahmut Oğul · Zeki Müren yorumuyla" },
    { id: "itirazim-var", order: 4, title: "İtirazım Var", videoId: "lWjhYR2bghI", mood: "Kadere bir itiraz: kalp daha hızlı çarpıyor.", credit: "Söz: İlhan Behlül Aktaş · Müzik: Rıfat Şanlıel" },
    { id: "agla-sevdam", order: 5, title: "Ağla Sevdam", videoId: "_WQ0jcji0ow", mood: "Ağlamak da büyümenin bir parçası.", credit: "Ağır Roman (1997) film müziği" },
    { id: "issizligin-ortasinda", order: 6, title: "Issızlığın Ortasında", videoId: "Z-m95DelB-g", mood: "Issızlığın tam ortasında tek başına bir ışık.", credit: "Moğollar · Söz: Cahit Berkay" },
    { id: "neydi-gunahim", order: 7, title: "Neydi Günahım", videoId: "3vYu_5HQPZ4", mood: "Cevapsız bir sorunun karanlığında tek bir spot.", credit: "Kayahan" },
    { id: "yuh-yuh", order: 8, title: "Yuh Yuh", videoId: "SUpvMpReNM0", mood: "Bir itiraz sesi büyüyor; damarlar ritimle titriyor.", credit: "Söz-Müzik: Aşık Mahzuni Şerif · Selda Bağcan yorumuyla" },
    { id: "nem-kaldi", order: 9, title: "Nem Kaldı", videoId: "cHuErdXbMgM", mood: "Toprak paylaşılmış; geriye bir türkü kalmış.", credit: "Söz-Müzik: Aşık Mahzuni Şerif · Cem Karaca yorumuyla" },
  ],
  device: "desktop",
  secrets: [
    { id: "kara-yagmur", title: "Yağmurda Simsiyah", text: "İsyanın ortasında kara yağmurun altında durdun. Bazen isyan, ıslanmayı göze almaktır." },
    { id: "kukla", title: "İpleri Kopmuş", text: "İpleri kopmuş bir kukla. Artık kimsenin oyuncağı değil; biraz yalnız ama özgür." },
    { id: "mektup", title: "Damgalı Mektup", text: "Zarfın üstünde silik bir cezaevi damgası. Arkasında tek kelime: 'Aldırma.'" },
    { id: "damla", title: "Beş Damla", text: "Duvardan sızan beş damlayı avucunda topladın. Çeşme kurumuş ama hatıra hâlâ sızıyor." },
    { id: "testi", title: "Kırık Testi", text: "Çeşmeye son gidişten kalmış kırık bir testi. Dibinde hâlâ bir yudum su var." },
    { id: "dilekce", title: "İtiraz Dilekçesi", text: "Kadere yazılmış bir itiraz dilekçesi. Cevap: 'Talebiniz değerlendirmeye alınmıştır. Tahmini süre: bir ömür.'" },
    { id: "cehennem", title: "Burası Cehennem Değil", text: "Kızıl halkaların ortasında durdun. Sıcak, evet; ama burası cehennem değil, anne karnı." },
    { id: "klarnet", title: "Utangaç Klarnet", text: "Kendi kendine çalmaya başlayan bir klarnet. Sen bakınca utanıp sustu." },
    { id: "bos-saray", title: "Boş Saray", text: "Hanlar saraylar boşalmış; geriye bir tabure ve bir çay bardağı kalmış. Çay hâlâ sıcak." },
    { id: "saz-telleri", title: "Kesik Teller", text: "Telleri kesilmiş bir saz. Yine de dimdik duruyor." },
    { id: "uyanis", title: "Uyanış", text: "Kâbusun ortasında zıpladın ve uyandın. Bu sefer uyumak istemiyorsun." },
    { id: "kerem-tuyu", title: "Kerem'in Tüyü", text: "Kerem gibi yanan bir tüy. Dokununca kül olmuyor; sadece ısıtıyor." },
    { id: "felekten-gece", title: "Çalınan Gece", text: "Tavandan bir yıldız kopardın; kaderden bir geceyi geri aldın. Kimseye söyleme." },
    { id: "yuhla", title: "Meydanla Birlikte", text: "Meydanla birlikte on kez bağırdın. Haksızlık edenler kulaklarını tıkadı." },
    { id: "muska", title: "Boş Muska", text: "Muskayı açtın: içi boş. Üstünde tek satır: 'Muska yok, yalnızca vicdan.'" },
    { id: "tapu", title: "Dünyanın Tapusu", text: "Tapuda yazan: 'Dünya — sahibi herkes, parseli yok.' Mühür silik." },
    { id: "dikili-tas", title: "Dikili Taş", text: "Bir dikili taş. Üstüne kazınmış tek kelime: 'kaldı'." },
    { id: "soz-sinavi", title: "Ezberden", text: "Sınavı geçtin: seni büyüten şarkıları sen de ezbere biliyormuşsun." },
  ],
  hub: {
    releaseType: "album",
    artistUrl: "https://www.instagram.com/haykocepkin",
    path: "worlds/beni-buyuten-sarkilar/",
    summary:
      "Hayko Cepkin'in büyürken dinlediği arabesk, Türk sanat müziği ve Anadolu rock klasiklerini kendi sert rock diliyle yeniden yorumladığı albüm. Kayahan'dan Zeki Müren'e, Selda Bağcan'dan Moğollar'a uzanan dokuz şarkı.",
    facts: [
      ["Yayın", "29 Aralık 2015"],
      ["Plak şirketi", "DMC"],
      ["Parça", "9 · 31 dakika"],
      ["Tür", "Rock · cover albüm"],
      ["Kaynaklar", "Arabesk, Türk sanat müziği, Anadolu rock"],
    ],
    world: {
      name: "Rahim",
      duration: "Albümün tamamı için ~35 dk · yalnızca masaüstü",
      highlights: [
        "Kapaktaki anne karnının içindesin: damarlı zar, kalp atışı, arkadan sızan sıcak ışık.",
        "Dokuz anı kabarcığı bebeğin çevresinde süzülür; her birinde bir plak var.",
        "Her şarkı bir ay: bebek büyür, kalp hızlanır, zar incelir.",
        "Her şarkının zara düşen bir gölge oyunu var: yağmurda bir bank, parmaklıkların ardında deniz, bir çeşme, yumruklar, Galata'da şemsiye, tek bir ağaç, bir spot, saz ve meydan, devrilen çitler.",
        "Anıya dokununca sahne tamamlanır ve bebek tekmeler.",
      ],
    },
    listenUrl: "https://www.youtube.com/playlist?list=OLAK5uy_lWVHOqxgY9f3ABc2Y-i7gYRyBZu-AbOhQ",
  },
};
