import type { AlbumData } from "../../engine/album";

export const ALBUM: AlbumData = {
  meta: {
    id: "mukemmel-bosluk",
    artist: "Redd",
    album: "Mükemmel Boşluk",
    year: "2016",
    cover: "covers/mukemmel-bosluk-cover.jpg",
    accent: "#c8212c",
    accentInk: "#ffffff",
    displayFont: "'Cinzel', serif",
    font3d: "cinzel-400",
    description:
      "Kapaktaki siyah volkanik kraterdesin. Beyaz gökyüzünde dev bir figür asılı duruyor; kraterin her yanına 12 plak dağılmış. Her plak bir şarkı, her şarkı dünyayı başka bir boşluğa çeviriyor.",
    mechanic: {
      name: "Hafifleme",
      text: "Plakları istediğin sırayla bul ve gramofona tak. Her şarkı krateri kendi sahnesine çevirir ve sana bir şey yaptırır: gemileri yakarsın, kırık kalpleri onarırsın, ormanı küle bırakırsın. Dinlediğin her şarkı yerçekimini azaltır; son şarkı bittiğinde figürün yanına yükselirsin.",
    },
    controls: [
      { keys: "W A S D", label: "Yürü" },
      { keys: "Fare", label: "Bak" },
      { keys: "Shift", label: "Koş" },
      { keys: "Boşluk", label: "Zıpla / süzül" },
      { keys: "E", label: "Plağı al · tak · şarkının eylemi" },
      { keys: "Q", label: "Elindekini bırak" },
      { keys: "R", label: "Çal / durdur" },
      { keys: "G", label: "Gramofonu kucağına al / yere koy" },
      { keys: "V", label: "Şarkının klibini izle / serbest dolaş" },
      { keys: "K", label: "Klibi kapat / aç (müzik sürer)" },
      { keys: "T", label: "Bakış açısı: birinci / üçüncü kişi" },
      { keys: "F", label: "El fenerini aç / kapat" },
      { keys: "ESC", label: "Menü ve ayarlar" },
    ],
    credits: [
      "Redd — Mükemmel Boşluk · 4 Mart 2016 · Pasaj Müzik",
      "Doğan Duru · Güneş Duru · Berke Özgümüş",
      "Miks: Mert Medeni · Mastering: Evren Göknar",
      "Şarkılar resmi YouTube kaynaklarından çalınır.",
    ],
  },
  tracks: [
    { id: "kalpsiz-romantik", order: 1, title: "Kalpsiz Romantik", videoId: "VjbqcO8zBwI", mood: "Denize bırakılmış gemiler yanıyor; kaçmak da bir çeşit bağlılık." },
    { id: "kaniyorduk", order: 2, title: "Kanıyorduk", videoId: "-ixXF3l96vo", mood: "Uzaktan bakınca her şey yıldız gibi güzel; yaklaştıkça sızlıyor." },
    { id: "ask-virus", order: 3, title: "Aşk, Virüs", videoId: "HAUU7azAcoo", mood: "Bir isim kana karışınca bütün krater ona bulaşıyor." },
    { id: "onlar-bile-uzulurler", order: 4, title: "Onlar Bile Üzülürler", videoId: "cFVbcbwccko", mood: "Kırık kalplerin müzesinde taşlar bile yas tutuyor." },
    { id: "bugun-herkes-olsun-istedim", order: 5, title: "Bugün Herkes Ölsün İstedim", videoId: "aVihRO0sm8M", mood: "Zaman durdu. Gökyüzü tam ortasından yarıldı." },
    { id: "senden-vazgeceli-cok-oldu", order: 6, title: "Senden Vazgeçeli Çok Oldu", videoId: "BHq6NHun35Y", mood: "İçindeki orman çoktan küle döndü; kül hâlâ yağıyor." },
    { id: "kafakafka", order: 7, title: "Kafakafka", videoId: "qJr6CMaMXW0", mood: "Buzdolabı, televizyon, radyo… boşlukta bir evin gürültüsü." },
    { id: "tam-bi-delilik", order: 8, title: "Tam Bi Delilik", videoId: "GatVbvQhxJA", mood: "Şehrin ışıkları yanıyor ama sokaklar bir cenaze kadar sessiz." },
    { id: "sextronot", order: 9, title: "Sextronot", videoId: "a9yw2897ZzA", mood: "Geri sayım bitti; yerçekimi seni bırakıyor." },
    { id: "itiraf", order: 10, title: "İtiraf", videoId: "pC8ZapalGDs", mood: "Yere dökülen her itiraf alev alıyor; yol merkeze çıkıyor." },
    { id: "boslukta-dans", order: 11, title: "Boşlukta Dans", videoId: "Lk-T4tMGiJw", mood: "Evsiz, isimsiz, ağırlıksız: boşlukta dans et." },
    { id: "hala-seni-cok-ozluyorum", order: 12, title: "Hala Seni Çok Özlüyorum", videoId: "sVj9CKndAsQ", mood: "Yara kapanmıyor. Ama boşluk artık mükemmel." },
  ],
  device: "mobile-demo",
  demoTracks: ["ask-virus", "kaniyorduk", "sextronot", "boslukta-dans"],
  secrets: [
    { id: "kalpsiz-sise", title: "Denizlerden Mektup", text: "Sayın Kalpsiz Romantik, bu ay yakılan gemi sayısı rekor kırdı. Balıklar şikâyetçi. Saygılarımızla, Denizler." },
    { id: "kalpsiz-demir", title: "Kilitli Oda", text: "Cam odanın kilidini üç kez zorladın. Başkalarının zihnine attığı demir kilitli kalır; o kapıyı içeriden kimse açamaz." },
    { id: "kaniyorduk-kitap", title: "Kurşun Kalem Notu", text: "Sayfanın kenarında silik bir not: 'Devi yenemedi ama iyi dövüştü. Sayfa 88.'" },
    { id: "kaniyorduk-yarim-ay", title: "Yarım Ay", text: "Ayı tamamlamayı denedin; bir an dolunay oldu, sonra yine yarım kaldı. Bazı şeyler yarımken güzel." },
    { id: "ask-hecele", title: "Hecelerine Kadar", text: "Adını on kez haykırdın; krater artık onu heceliyor. Yankılar da yoruldu." },
    { id: "ask-sakiz", title: "Tadı Kaçmış", text: "Taşa yapışmış, tadı çoktan gitmiş bir sakız. Kimse böyle bir kenara atılmayı hak etmez." },
    { id: "onlar-bilet", title: "Müze Bileti", text: "Kırık Kalpler Müzesi — tam bilet. Giriş ücretsiz, çıkış yok. Arkasında el yazısı: 'yine geldin.'" },
    { id: "onlar-cicek", title: "Bataklık Çiçeği", text: "Rengârenk bataklıkta açan tek gerçek renk. Batarken bile güzel kokuyor." },
    { id: "bugun-saat", title: "Duran Saat", text: "Cep saati tam ayrıldığınız dakikada durmuş. Kurmayı denedin; kurulmuyor." },
    { id: "bugun-yanki", title: "Yankı", text: "Sessizliğe seslendin. Biri cevap verdi: kendi sesin. Sadece yankı." },
    { id: "senden-tabela", title: "Eve Giden Yol", text: "Tabela her yönü gösteriyor: 'EV — 3 km'. Hangisini seçsen aynı mesafe." },
    { id: "senden-canavar", title: "Asıl Canavar", text: "İçinde doğan canavar aslında küçük ve biraz utangaç. Göz göze gelince ağacın arkasına saklandı." },
    { id: "kafka-limon", title: "Buzdolabı", text: "Her şey yenmiş. Geriye bir limon ve bir kitap kalmış: Dönüşüm." },
    { id: "kafka-kumanda", title: "Kumanda", text: "Üç kez kanal değiştirdin; her kanalda aynı bağıran adam. Kumandayı yere bıraktın." },
    { id: "delilik-cicek", title: "Kendine Çiçek", text: "Köşedeki çiçekçiden kendine çiçek aldın. Delilik belki; ama güzel bir delilik." },
    { id: "delilik-ucurum", title: "Uçurumun Kenarı", text: "Banka oturdun, aşağı baktın ve geri döndün. İyi ki döndün." },
    { id: "sextronot-uydu", title: "Kaç Uydun Var?", text: "Uydularından birine dokundun. Cevap basit: bir tane, o da yörüngesinden çıkmak üzere." },
    { id: "sextronot-bowie", title: "Ground Control", text: "Bütün halkalara dokundun. Telsizde bir cızırtı: 'Major Tom, kraterden çok iyi görünüyorsun.'" },
    { id: "itiraf-benzin", title: "Boş Bidon", text: "Benzin bidonu bomboş. Artık kimseyi yakmıyorsun; kendini bile." },
    { id: "itiraf-merkez", title: "Ateşin Ortası", text: "İtirafın tam ortasında duruyorsun. Ateş ısıtıyor ama yakmıyor." },
    { id: "dans-kelebek", title: "Çelimsiz Kelebek", text: "Kelebeği avucuna aldın; kanatları renkli, bir o kadar ince. Bıraktın, boşlukta dans ederek uzaklaştı." },
    { id: "dans-donus", title: "Beş Tur", text: "Beş tur döndün ve başın dönmedi. Boşlukta dönmek serbest; düşecek bir yer yok." },
    { id: "hala-yara-bandi", title: "Yara Bandı", text: "Dev bir yara bandı yapıştırdın; tutmadı. Bazı yaralar açık kalmayı seçer." },
    { id: "hala-gulen-yuz", title: "Gülen Yüz", text: "Birisi toza gülen bir yüz çizmiş; gözünden tek bir damla akıyor." },
    { id: "soz-sinavi", title: "Ezberden", text: "Kürsüdeki sınavı geçtin: on sorunun en az sekizini bildin. Boşluk ezberlenmez sanırdın; meğer sen onu çoktan ezberlemişsin." },
  ],
  hub: {
    releaseType: "album",
    artistUrl: "https://www.instagram.com/reddseyirdefter",
    path: "worlds/mukemmel-bosluk/",
    summary:
      "Redd'in altıncı stüdyo albümü. Grup yaklaşık iki yıl hazırlandığı bu kayıtta sert rock çizgisini geri çekip new wave, post-punk ve synth-pop dokularına yöneldi. Şarkılar tek tek değil, tek bir boşluk hissi etrafında bütünlüklü ilerler.",
    facts: [
      ["Yayın", "4 Mart 2016"],
      ["Plak şirketi", "Pasaj Müzik"],
      ["Parça", "12 · 49 dakika"],
      ["Tür", "Alternatif rock · new wave · synth-pop"],
      ["Kadro", "Doğan Duru · Güneş Duru · Berke Özgümüş"],
      ["Miks / Mastering", "Mert Medeni / Evren Göknar"],
    ],
    world: {
      name: "Krater",
      duration: "Albümün tamamı için ~50 dk · telefonda 4 şarkılık demo",
      highlights: [
        "Kapaktaki kraterde, havada asılı dev figürün altında yürürsün.",
        "12 plak her oturumda farklı yerlere dağılır; istediğin sırayla bulursun.",
        "Her şarkının kendi sahnesi ve eylemi var: denizdeki gemileri yak, kanayan yıldızları avuçla, kırık kalpleri altınla onar, donmuş zamanı kır, şehrin ışıklarını söndür, geri sayımla fırla, mumları yakarak merkeze in.",
        "Kapak Noktası'nda sahne kapakla birebir hizalanır; fotoğrafını çekebilirsin.",
      ],
    },
    listenUrl: "https://www.youtube.com/playlist?list=PLN7Mz22vezPbWRsVI4PnhcVp34U08e6X8",
  },
};
