/** Hub arayüz metinleri — tek kaynak. */
export const COPY = {
  brand: "AudioRoom",
  tagline: "Albüm evrenleri",
  searchPlaceholder: "Şarkı, albüm veya sanatçı ara",
  searchLabel: "Kütüphanede ara",
  filterAll: "Tümü",
  filterAvailable: "Yayında",
  filterSoon: "Yakında",
  shelfLabel: "Albüm rafı",
  previous: "Önceki albüm",
  next: "Sonraki albüm",
  random: "Rastgele",
  enter: "Evrene gir",
  versionsTitle: "Hangi sürümle girmek istersin?",
  versionsLead: "Eski sürümler silinmez; her biri kendi hâliyle oynanır.",
  versionsClose: "Sürüm seçiciyi kapat",
  versionsLast: "Son girdiğin",
  versionsNone: (phone: boolean) =>
    phone ? "Telefonda açılmaz. Telefonda yalnızca Mükemmel Boşluk'un Sürüm 1'i oynanır." : "Bu sürüm klavye ve fare için; dokunmatik ekranda açılmaz.",
  versionsEnter: (number: number, demo: boolean) => (demo ? `Sürüm ${number} · demoyu başlat` : `Sürüm ${number} ile gir`),
  versionsBadge: (count: number) => `${count} sürüm`,
  oldVersionHere: (phone: boolean) =>
    phone ? "Sürüm 2 bilgisayar ve tablette açılır; telefonda Sürüm 1 oynanır." : "Sürüm 2 bilgisayarda açılır; tablette Sürüm 1 oynanır.",
  enterDemo: "Demoyu başlat",
  desktopOnly: (phone: boolean) => (phone ? "Geniş ekranda açılır" : "Bilgisayarda açılır"),
  soon: "Yakında",
  albumPage: "Albüm sayfası",
  back: "‹ Kütüphane",
  listen: "YouTube'da dinle ↗",
  artist: "Instagram ↗",
  resetProgress: "Evreni sıfırla",
  resetConfirm: "Plaklar, final ve gizli keşifler silinsin mi? Bu geri alınamaz.",
  resetYes: "Evet, sıfırla",
  resetNo: "Vazgeç",
  resetDone: "Evren sıfırlandı. Her şey ilk günkü gibi.",
  secretsTitle: (found: number, total: number) => `Gizli keşifler · ${found} / ${total}`,
  secretsNone: (total: number) => `Bu evrende ${total} gizli keşif saklı. Şarkıların içine iyi bak: bazıları yalnızca belli bir dizede belirir.`,
  secretsLeft: (left: number) => (left === 0 ? "Hepsini buldun." : `Kalan ${left} keşif evrende saklı.`),
  secretsBadge: (found: number, total: number) => `✦ ${found} / ${total} keşif`,
  emptyTitle: "Sonuç bulunamadı",
  emptyText: "Başka bir şarkı, albüm ya da sanatçı adı dene.",
  clearFilters: "Filtreleri temizle",
  worldTitle: (name: string) => `Evren · ${name}`,
  albumTitle: "Albüm hakkında",
  tracksTitle: "Parçalar",
  mechanicLabel: "Mekanik",
  listened: "Dinlendi",
  releaseType: { album: "Albüm", single: "Single", ep: "EP" } as const,
  status: { available: "Yayında", soon: "Yakında" },
  device: {
    "mobile-demo": "Geniş ekran · telefonda Sürüm 1",
    desktop: "Yalnızca masaüstü",
  } as const,
  desktopOnlyNote: (phone: boolean) =>
    phone
      ? "Bu evren bilgisayar ve tablet için. Telefonda yalnızca Mükemmel Boşluk'un Sürüm 1'i açılır."
      : "Bu evren klavye ve fare için tasarlandı; dokunmatik ekranda açılmaz.",
  demoNote: "Tablette 4 şarkılık sade bir demo açılır. Evrenin tamamı bilgisayarda.",
  soonNote: "Bu albümün evreni hazırlanıyor.",
  progress: (found: number, total: number) => (total === 1 ? "Dinlendi" : `${found} / ${total} plak dinlendi`),
  completed: "Tamamlandı",
  footer: (year: number) => `© ${year} AudioRoom · Powered by MeMoDe · v${__APP_VERSION__}`,
  notFoundTitle: "Bulunamadı",
  notFoundText: "Aradığın albüm ya da sayfa burada yok; adres değişmiş olabilir.",
  notFoundAction: "Kütüphaneye dön",
  privacyLink: "Gizlilik",
  privacyTitle: "Gizlilik",
  privacyYoutube: "YouTube (Google) gizlilik politikası ↗",
  privacy: [
    ["Hesap ve takip yok", "AudioRoom'da üyelik, giriş, reklam ya da analitik yok. Sunucuya kişisel veri gönderilmez; site yalnızca statik dosyalardan oluşur."],
    ["Tarayıcında saklananlar", "Grafik, ses ve kontrol ayarların ile evrenlerde bulduğun plaklar yalnızca bu tarayıcıda (localStorage) tutulur. Albüm sayfasındaki \"Evreni sıfırla\" ile ya da tarayıcı verilerini silerek kaldırabilirsin."],
    ["Müzik ve YouTube", "Şarkılar YouTube'un gizlilik geliştirilmiş oynatıcısıyla (youtube-nocookie.com) çalar. Oynatıcı ancak bir evrende plağı gramofona taktığında yüklenir; o andan sonra YouTube'un kendi gizlilik politikası geçerlidir."],
    ["Dosyalar ve bağlantılar", "Kapaklar, modeller ve yazı tipleri bu siteden sunulur; üçüncü taraf yazı tipi ya da CDN kullanılmaz. Instagram ve YouTube bağlantıları yeni sekmede açılır. Kapaklar ve şarkılar sahiplerine aittir."],
  ] as ReadonlyArray<readonly [string, string]>,
};
